#pragma once

#include "plotpp/IPlot.hpp"
#include "plotpp/Figure.hpp"
#include "plotpp/Multiplot.hpp"
#include "plotpp/Line.hpp"
#include "plotpp/Points.hpp"
#include "plotpp/Heatmap.hpp"
#include "plotpp/Arrows.hpp"
#include "plotpp/XError.hpp"
#include "plotpp/YError.hpp"
#include "plotpp/XYError.hpp"
#include "plotpp/Boxes.hpp"
#include "plotpp/Color.hpp"
#include "plotpp/Colormaps.hpp"
#include "plotpp/Boxplot.hpp"
#include "plotpp/Circle.hpp"
#include "plotpp/Piechart.hpp"